Updating BDF Analyzer for staggered scheme support
mgroupntua/MSolve.Analyzers pull request #7
Opened 2022-09-22 13:50 UTC by TheoChristo

2022-09-22 19:33 UTC, GoatOfRafin commented on src/MGroup.NumericalAnalyzers/Dynamic/BDFDynamicAnalyzer.cs
> +			Console.WriteLine("BDF step: {0}", currentTimeStep);
All debug info should be output at Debug and not at Console

2022-09-22 19:34 UTC, GoatOfRafin requested changes
Console.WriteLine should be Debug.WriteLine

2022-09-23 10:06 UTC, TheoChristo commented
Updated code, replacing Console.WriteLine with Debug.WriteLine and removing unnecessary comments

2022-09-23 11:13 UTC, GoatOfRafin approved these changes

2022-09-23 11:18 UTC, merged